// Generated by CoffeeScript 1.3.3
(function() {
  var insert, oldElement;

  oldElement = document.getElementsByTagName('script')[0];

  insert = function(tagName, url, id) {
    var newElement;
    if (document.getElementById(id)) {
      return;
    }
    newElement = document.createElement(tagName);
    newElement.src = url;
    id && (newElement.id = id);
    return oldElement.parentNode.insertBefore(newElement, oldElement);
  };

}).call(this);
