window:
  width: 1280
  height: 720
fps: 60.0
gravity:
  x: 0.0
  y: -200.0
player:
  position: [640, 460]
  mass: 1.0
  friction: 0.5
  elasticity: 0.5
  radius: 0.0
shapes:
  - position: [640, 0]
    mass: 1.0
    friction: 0.5
    elasticity: 0.5
    radius: 0.0
    vertices: [[1, 10], [1280, 10], [1280, 1], [1, 1]]
  
