window:
  width: 1280
  height: 720
opengl:
  sample_buffers: 1
  samples: 4
fps: 120.0
gravity:
  x: 0.0
  y: -250.0
shapes:
  # Box.
  - mass: 2
    position: [640, 460]
    friction: 0.5
    elasticity: 0.5
    vertices: [[-10, -10], [-10, 10], [10, 10], [10, -10]]
  # Box 2.
  - mass: 1
    position: [625, 300]
    friction: 0.5
    elasticity: 1
    vertices: [[-10, -10], [-10, 10], [10, 10], [10, -10]]
  # Floor.
  - mass: null
    position: [0, 0]
    friction: 1
    elasticity: 0.5
    vertices: [[0, 5], [1280, 5], [1280, 0], [0, 0]]
  # Left wall.
  - mass: null
    position: [0, 5]
    friction: 0.5
    elasticity: 0.5
    vertices: [[0, 0], [0, 710], [8, 710], [8, 0]]
  # Ceiling.
  - mass: null
    position: [0, 715]
    friction: 0.5
    elasticity: 0.5
    vertices: [[0, 5], [1280, 5], [1280, 0], [0, 0]]
  # Right wall.
  - mass: null
    position: [1272, 5]
    friction: 0.5
    elasticity: 0.5
    vertices: [[0, 0], [0, 710], [8, 710], [8, 0]]
  
