graphics:
  fps: 60.0
  opengl:
    sample_buffers: 1
    samples: 4
  window:
    width: 1280
    height: 720

physics:
  damping: 0
  limit: 300
  gravity:
    x: 0.0
    y: -100

paths:
  objects: objects.yaml
  bindings: bindings.yaml
