window:
  width: 1280
  height: 720
opengl:
  sample_buffers: 1
  samples: 4
fps: 60.0
gravity:
  x: 0.0
  y: -500.0
shapes:
  # Player.
  - mass: 1
    type: player
    position: [645, 500]
    friction: 1
    elasticity: 0.5
    vertices: [[-10, -10], [-10, 10], [10, 10], [10, -10]]
  # Box 1.
  - mass: 0.1
    type: poly
    position: [640, 460]
    friction: 0.5
    elasticity: 0.5
    vertices: [[-10, -10], [-10, 10], [10, 10], [10, -10]]
  # Box 2.
  - mass: 0.05
    type: poly
    position: [630, 400]
    friction: 0.5
    elasticity: 0.9
    vertices: [[-20, -20], [-20, 20], [20, 20], [20, -20]]
  # Box 3.
  - mass: 0.05
    type: poly
    position: [630, 50]
    friction: 0.2
    elasticity: 0.9
    vertices: [[-30, -30], [-30, 30], [30, 30], [30, -30]]
  # Floor.
  - mass: null
    type: poly
    position: [0, 0]
    friction: 1
    elasticity: 0.5
    vertices: [[0, 5], [1280, 5], [1280, 0], [0, 0]]
  # Left wall.
  - mass: null
    type: poly
    position: [0, 5]
    friction: 0.5
    elasticity: 0.5
    vertices: [[0, 0], [0, 710], [8, 710], [8, 0]]
  # Ceiling.
  - mass: null
    type: poly
    position: [0, 715]
    friction: 0.5
    elasticity: 0.5
    vertices: [[0, 5], [1280, 5], [1280, 0], [0, 0]]
  # Right wall.
  - mass: null
    type: poly
    position: [1272, 5]
    friction: 0.5
    elasticity: 0.5
    vertices: [[0, 0], [0, 710], [8, 710], [8, 0]]
  
