aliases:
  - &base
      graphics: &base_graphics
        color: !!python/tuple [0.2, 0.2, 0.2, 1]
      id: -1
      physics: &base_physics
        body: &base_physics_body
          mass: null
          moment: null
          position: !!python/tuple [0, 0]
        shape: &base_physics_shape
          collision_type: -1
          elasticity: 0.5
          friction: 0.5
          radius: 0
        type: base
  - &circle
      <<: *base
      physics: &circle_physics
        <<: *base_physics
        shape: &circle_physics_shape
          <<: *base_physics_shape
          offset: !!python/tuple [0, 0]
          radius: 10
        type: circle
  - &poly
      <<: *base
      physics: &poly_physics
        <<: *base_physics
        shape: &poly_physics_shape
          <<: *base_physics_shape
          offset: !!python/tuple [0, 0]
          type: poly
          vertices: 
            - !!python/tuple [-10, -10]
            - !!python/tuple [10, -10]
            - !!python/tuple [10, 10]
            - !!python/tuple [-10, 10]
        type: poly
  - &segment
      <<: *base
      physics: &segment_physics
        <<: *base_physics
        shape: &segment_physics_shape
          <<: *base_physics_shape
          a: !!python/tuple [-10, 0]
          b: !!python/tuple [10, 0]
          radius: 2
        type: segment

objects:
  # Player.
  - <<: *circle
    id: 0
    physics:
      <<: *circle_physics
      body:
        <<: *base_physics_body
        mass: 1
        position: !!python/tuple [640, 100]
      impulse:
        left: -10
        right: 10
        up: 350
      shape:
        <<: *circle_physics_shape
        collision_type: 0
        elasticity: 0

  # Platform 1.
  - <<: *poly
    id: 1
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [245, 65]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-240, -5]
          - !!python/tuple [240, -5]
          - !!python/tuple [240, 5]
          - !!python/tuple [-240, 5]

  # Platform 1 bottom.
  - <<: *poly
    id: 7
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [245, 55]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-240, -5]
          - !!python/tuple [240, -5]
          - !!python/tuple [240, 5]
          - !!python/tuple [-240, 5]

  # Floor.
  - <<: *poly
    id: 2
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [640, -195]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-640, -200]
          - !!python/tuple [640, -200]
          - !!python/tuple [640, 200]
          - !!python/tuple [-640, 200]

  # Ceiling.
  - <<: *poly
    id: 3
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [640, 915]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-640, -200]
          - !!python/tuple [640, -200]
          - !!python/tuple [640, 200]
          - !!python/tuple [-640, 200]

  # Left wall.
  - <<: *poly
    id: 4
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [-195, 360]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-200, -360]
          - !!python/tuple [200, -360]
          - !!python/tuple [200, 360]
          - !!python/tuple [-200, 360]
            
  # Right wall.
  - <<: *poly
    id: 5
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1475, 360]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-200, -360]
          - !!python/tuple [200, -360]
          - !!python/tuple [200, 360]
          - !!python/tuple [-200, 360]


  # Platform 8.
  - <<: *poly
    id: 8
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [600, 200]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-5, -5]
          - !!python/tuple [5, -5]
          - !!python/tuple [5, 5]
          - !!python/tuple [-5, 5]

  # Platform 9.
  - <<: *poly
    id: 9
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [600, 220]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-5, -5]
          - !!python/tuple [5, -5]
          - !!python/tuple [5, 5]
          - !!python/tuple [-5, 5]

  # Platform 10.
  - <<: *poly
    id: 10
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [600, 240]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-5, -5]
          - !!python/tuple [5, -5]
          - !!python/tuple [5, 5]
          - !!python/tuple [-5, 5]

  # Platform 11.
  - <<: *poly
    id: 11
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [640, 200]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-5, -5]
          - !!python/tuple [5, -5]
          - !!python/tuple [5, 5]
          - !!python/tuple [-5, 5]

  # Platform 12.
  - <<: *poly
    id: 12
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [760, 200]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-10, -10]
          - !!python/tuple [10, -10]
          - !!python/tuple [10, 10]
          - !!python/tuple [-10, 10]
            
  # Platform 13.
  - <<: *poly
    id: 13
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [900, 200]
      shape:
        <<: *poly_physics_shape
        vertices:
          - !!python/tuple [-10, -10]
          - !!python/tuple [100, -10]
          - !!python/tuple [100, 10]
          - !!python/tuple [-10, 10]
            
  # Platform 14.
  - <<: *poly
    id: 14
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [850, 500]
        mass: 1
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-10, -10]
          - !!python/tuple [10, -10]
          - !!python/tuple [10, 10]
          - !!python/tuple [-10, 10]

  # Platform 15.
  - <<: *poly
    id: 15
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1150, 500]
        mass: 0.5
        elasticity: 0.9
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-20, -20]
          - !!python/tuple [20, -20]
          - !!python/tuple [20, 20]
          - !!python/tuple [-20, 20]

  # Platform 16.
  - <<: *poly
    id: 16
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1100, 115]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-2, -2]
          - !!python/tuple [2, -2]
          - !!python/tuple [2, 2]
          - !!python/tuple [-2, 2]

  # Platform 17.
  - <<: *poly
    id: 17
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1100, 110]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-2, -2]
          - !!python/tuple [2, -2]
          - !!python/tuple [2, 2]
          - !!python/tuple [-2, 2]

  # Platform 18.
  - <<: *poly
    id: 18
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1100, 105]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-2, -2]
          - !!python/tuple [2, -2]
          - !!python/tuple [2, 2]
          - !!python/tuple [-2, 2]

  # Platform 19.
  - <<: *poly
    id: 19
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1100, 100]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-2, -2]
          - !!python/tuple [2, -2]
          - !!python/tuple [2, 2]
          - !!python/tuple [-2, 2]
            
  # Platform 20.
  - <<: *poly
    id: 20
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1100, 95]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-2, -2]
          - !!python/tuple [2, -2]
          - !!python/tuple [2, 2]
          - !!python/tuple [-2, 2]

  # Platform 21.
  - <<: *poly
    id: 21
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1100, 90]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-2, -2]
          - !!python/tuple [2, -2]
          - !!python/tuple [2, 2]
          - !!python/tuple [-2, 2]

  # Platform 22.
  - <<: *poly
    id: 22
    physics:
      <<: *poly_physics
      body:
        <<: *base_physics_body
        position: !!python/tuple [1100, 85]
      shape:
        <<: *poly_physics_shape
        collision_type: 1
        vertices:
          - !!python/tuple [-2, -2]
          - !!python/tuple [2, -2]
          - !!python/tuple [2, 2]
          - !!python/tuple [-2, 2]
