graphics:
  background: !!python/tuple [0.2, 0.2, 0.2, 1]
  fps: 60.0
  opengl:
    sample_buffers: 1
    samples: 4
  window:
    width: 1280
    height: 720

physics:
  damping: 0.1
  limit: 300
  gravity: !!python/tuple [0.0, -500]
  ray:
    length: 1469 # diagonal length of window.

paths:
  objects: config/objects.yaml
  bindings: config/bindings.yaml
